name: Get Latest Tag Example

# Update 'push' and 'pull\_request' events to include both branches and tags
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Tag Name example
        run: |
          # Display all environment variables starting with 'GITHUB_'
          env | grep ^GITHUB_
          echo "Tag name from GITHUB_REF_NAME : $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name : ${{  github.ref_name }}"
          echo "Tag name from github.event : ${{ github.event.head_commit.ref }}"
