name: Get Latest Tag Example

# Update 'push' and 'pull\_request' events to include both branches and tags
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Describe Tags
        run: |
          git fetch --prune --unshallow
          latest_tag=$(git describe --tags --abbrev=0 HEAD~)
          echo "Latest Tag: $latest_tag"
